AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dynamoapp
  Sample SAM Template for dynamoapp

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  DynamoDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DynamoDBFunction/
      Handler: dynamoapp.App::handleRequest
      Runtime: java17
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: !GetAtt UserTable.Arn
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        DynamoDBFunction:
          Type: Api 
          Properties:
            Path: /{proxy+}
            Method: any

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: userDB
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"